services:
    elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}"
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
        volumes:
            - es-data-9:/usr/share/elasticsearch/data
            - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
            - es-plugins:/usr/share/elasticsearch/plugins
        ports:
            - "9200:9200"
            - "9300:9300"

    logstash:
        depends_on:
            - elasticsearch
        image: "docker.elastic.co/logstash/logstash:${ES_VERSION}"
        volumes:
            - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
        ports:
            - "5044:5044"
        links:
            - elasticsearch

    kibana:
        depends_on:
            - elasticsearch
        image: "docker.elastic.co/kibana/kibana:${ES_VERSION}"
        volumes:
            - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
        ports:
            - "5601:5601"
        links:
            - elasticsearch

    filebeat:
        depends_on:
            - elasticsearch
            - logstash
        image: "docker.elastic.co/beats/filebeat:${ES_VERSION}"
        user: root
        environment:
            - strict.perms=false
        volumes:
            - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
            - ./logs/filebeat:/usr/share/filebeat/logs:rw
            - filebeat-data:/usr/share/filebeat/data:rw
        links:
            - logstash

volumes:
    es-data-9:
    es-plugins:
    filebeat-data:
